USE mdc_ch02;
-- A:
-- SELECT * FROM CUSTOMER;
-- SELECT * FROM INVOICE;
-- SELECT * FROM INVOICE_ITEM;


-- B:
-- SELECT FIRSTNAME, LASTNAME, PHONE FROM CUSTOMER;

 
-- C:
-- SELECT FIRSTNAME, LASTNAME, PHONE FROM CUSTOMER WHERE FIRSTNAME = "Nikki"; 

-- D:
