-- STATEMENT to display SKU & SKU_DESCRIPTION
-- SELECT SKU, SKU_DESCRIPTION FROM INVENTORY;  

-- STATEMENT TO DISPLAY SKU_DESCRIPTION & SKU 
-- SELECT SKU_DESCRIPTION, SKU FROM INVENTORY;

-- STATEMENT TO DISPLAY WAREHOUSEID
-- SELECT WarehouseId FROM INVENTORY;


-- DISPLAY UNIQUE WAREHOUSE IDS
-- SELECT DISTINCT WarehouseId FROM INVENTORY;

-- DISPLAY ALL COLUMNS WITHOUT *
-- SELECT WarehouseID, SKU_Description, QuantityOnHand, QuantityOnOrder FROM INVENTORY

-- DISPLAY ALL COLUMNS WITH * 
-- SELECT * FROM INVENTORY

-- DISPLAY ALL DATA ON PRODUCTS HAVING A QUANTITYONHAND GREATER THAN 0
-- SELECT QuantityOnHand FROM INVENTORY WHERE  QuantityOnHand > 0


-- DISPLAY SKU, SKU_Description FOR PRODUCTS HAVING QUANTITYONHAND EQUAL TO 0 
-- SELECT SKU, SKU_Description FROM INVENTORY WHERE QuantityOnHand = 0;

-- DISPLAY SKU, SKU_Description, WAREHOUSEID FOR PRODUCTS HAVING QUANTITYONHAND EQUAL TO 0, SORT IN ASCENDING ORDER ORDER BY WAREHOUSEID
-- SELECT SKU, SKU_Description FROM INVENTORY WHERE QuantityOnHand = 0 ORDER BY WarehouseID ASC


-- DISPLAY SKU, SKU_Description, WAREHOUSEID FOR PRODUCTS HAVING QUANTITYONHAND EQUAL TO 0, SORT IN ASCENDING ORDER ORDER BY WAREHOUSEID
-- SELECT SKU, SKU_Description FROM INVENTORY WHERE QuantityOnHand > 0 ORDER BY WarehouseID DESC

